sudo: required
services:
  - docker

before_script:

  # MySQL starts by default, resulting in a port conflict
  - sudo /etc/init.d/mysql stop

script:
  - docker-compose up -d --build
  - docker exec hashtags_app_1 python manage.py test

after_script:
  - docker images
  - bash <(curl -s https://codecov.io/bash)